### ISSUE TITLE
Beta to release (December)

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-chibitronics#134]
Release beta to release with these PRs and changes:
- [x] Fixes the SCOPE issue: https://github.com/Microsoft/pxt-chibitronics/issues/127
- [x] Fixes this issue with multiple editors open: https://github.com/Microsoft/pxt-chibitronics/issues/121
- [x] Hides all field editor pickers from JS
- [x] Refactor turn block into setPin https://github.com/Microsoft/pxt-chibitronics/pull/133
- [x] Fix Blinky example: https://github.com/Microsoft/pxt-chibitronics/issues/113
- [x] New sensing event block: https://github.com/Microsoft/pxt-chibitronics/issues/95
- [x] Fix sensing read block: https://github.com/Microsoft/pxt-chibitronics/pull/136

Releasing pxt-core stable 2.3

@jieq @bunnie @xobs @abchatra FYI

Once all the above fixes are in and tested, I shall release the beta bits.
